Update ci_boo_on_rdna4.yml (#2888)

diff --git a/.github/workflows/ci_boo_on_rdna4.yml b/.github/workflows/ci_boo_on_rdna4.yml
--- a/.github/workflows/ci_boo_on_rdna4.yml
+++ b/.github/workflows/ci_boo_on_rdna4.yml
@@ -82,23 +82,22 @@ jobs:
       with:
         python-version: ${{matrix.version}}
 
-    - name: Print System Information
-      run: |
-        echo "============ CPU Information ============"
-        lscpu
-        echo ""
-        echo "============ GPU Information ============"
-        rocm-smi || true
-        rocminfo || true
-        echo ""
-        echo "============ ROCM Version ============"
-        cat /opt/rocm/.info/version || echo "ROCM version file not found"
+    # - name: Print System Information
+    #   run: |
+    #     echo "============ CPU Information ============"
+    #     lscpu
+    #     echo ""
+    #     echo "============ GPU Information ============"
+    #     rocm-smi || true
+    #     rocminfo || true
+    #     echo ""
+    #     echo "============ ROCM Version ============"
+    #     cat /opt/rocm/.info/version || echo "ROCM version file not found"
 
     - name: Create Python venv
       run: |
         python -m venv ${VENV_DIR}
         source ${VENV_DIR}/bin/activate
-        sudo ln -s python3 /usr/bin/python || true
         echo "${VENV_DIR}/bin" >> $GITHUB_PATH
 
     - name: Install pip deps
